name: nextjs-together-llamaindex
version: '3.8'
networks:
  bridge:
    driver: bridge

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_API_HOSTNAME=http://backend:3000
    ports:
      - "3000:80"
    env_file:
      - ./frontend/.env
    environment:
      - NEXT_PUBLIC_API_HOSTNAME=http://backend:3000
    depends_on:
      - backend
    networks:
      - bridge

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:3000"
    env_file:
      - ./backend/.env
    networks:
      - bridge